### ISSUE TITLE
Introduce static analysis

### ISSUE THREAD

**Issue by szepeviktor** [godaddy-wordpress/coblocks#1391]
Simply

```
composer require --ignore-platform-reqs --dev szepeviktor/phpstan-wordpress
vendor/bin/phpstan analyze
```

`phpstan.neon.dist`

```yaml
includes:
    - vendor/szepeviktor/phpstan-wordpress/extension.neon
parameters:
# TODO    level: max
    level: 5
    inferPrivatePropertyTypeFromConstructor: true
    paths:
        - src/
    autoload_files:
        - class-coblocks.php
        - src/blocks/events/index.php
        - src/blocks/post-carousel/index.php
        - src/blocks/posts/index.php
        - src/blocks/share/index.php
        - src/blocks/social-profiles/index.php
```
