### ISSUE TITLE
ISBAT use Masonry block and have consistent layout across browsers

### ISSUE THREAD

**Issue by AnthonyLedesma** [godaddy-wordpress/coblocks#2265]
### Describe the bug:

It seems that Safari is displaying an inconsistent masonry layout compared to Chrome and Firefox. In the screenshots provided, we can see superfluous spacing that resides above the middle image. 

### To reproduce:

1. Add Masonry block.
2. Add images with varying heights (easier to see with more images).
3. Publish and view the page in Safari.

### Expected behavior:

Expect consistent Masonry layout in Chrome, Firefox, and Safari.

### Screenshots:

![image](https://user-images.githubusercontent.com/30462574/152573958-8a4ad5cf-e8a6-406e-b216-1356bcb26218.png)

![image](https://user-images.githubusercontent.com/30462574/152574030-774ae3c2-2f52-4664-a3c3-14c2643f7f72.png)
### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:

5.9

### Gutenberg version:

N/A

**Comment by AnthonyLedesma** [comment]
This CSS is a user-reported fix from WP.org. I was not able to achieve consistent results with just this.

```css
.wp-block-coblocks-gallery-masonry .wp-block-image {
	-webkit-margin-after: 0!important;
	padding-bottom: 1em!important;
}
@-moz-document url-prefix() {
	.wp-block-coblocks-gallery-masonry .wp-block-image {
		padding-bottom: 0!important;
	}
}
```
